site_name: NINA Data Management System (DMS)
repo_url: https://github.com/ninanor/dms

theme:
  name: material
  palette:
    primary: teal
    accent: indigo
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.sections
    - navigation.instant.prefetch
    - navigation.expand
    - navigation.path
    - toc.integrate
    - toc.follow
    - search.suggest
    - search.highlight
    - content.action.edit

edit_uri: edit/main/docs/

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_root_heading: true
  - neoteroi.mkdocsoad:
      use_pymdownx: true

nav:
- Introduction: index.md
- User:
  - Users: user/users.md
  - Projects: user/project.md
  - Services: user/services.md
  - Datasets: user/datasets.md
- Developers:
  - Structure: dev/structure.md
  - Setup: dev/setup.md
  - API: dev/api.md
  - Deployment: dev/deployment.md
  - Reference: dev/reference.md

watch:
  - docs
  - src

extra_css:
- css/mkdocsoad.css

markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tabbed:
      alternate_style: true
